<a href="https://colab.research.google.com/github/sudeepkanthala/ICP_3/blob/main/ICP_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
1. Create a class Employee and then do the following
• Create a data member to count the number of Employees
• Create a constructor to initialize name, family, salary, department
• Create a function to average salary
• Create a Fulltime Employee class and it should inherit the properties of Employee class
• Create the instances of Fulltime Employee class and Employee class and call their member functions

In [1]:
class Employee:

    empCount = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.empCount += 1

    def avgSalary(self):
        avg = self.salary
        print(f"Average Salary: {avg}")

class FullTimeEmployee(Employee):

    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

emp1 = Employee("John", "Doe", 50000, "IT")
emp2 = Employee("Jane", "Doe", 60000, "Sales")

ftemp1 = FullTimeEmployee("Jim", "Taylor", 70000, "Marketing")
ftemp2 = FullTimeEmployee("Mary", "Jones", 80000, "Engineering")

print(Employee.empCount)
emp1.avgSalary()
ftemp2.avgSalary()

4
Average Salary: 50000
Average Salary: 80000


In [ ]:
2. Numpy
Using NumPy create random vector of size 20 having only float in the range 1-20.
Then reshape the array to 4 by 5
Then replace the max in each row by 0 (axis=1)
(you can NOT implement it via for loop)

In [2]:
import numpy as np

# Create random vector of size 20 with floats between 1-20
vec = np.random.uniform(1, 20, 20)

# Reshape vector to 4 x 5 array
arr = vec.reshape(4, 5)

# Replace max in each row with 0
arr[np.arange(arr.shape[0]), arr.argmax(1)] = 0

print(arr)

[[ 2.63652822  6.48472014  9.08751619  0.          4.05244705]
 [15.76099623 16.12432779  0.         13.06703093  9.76084898]
 [11.98056146 12.69466689  0.         18.12258975 13.84737708]
 [ 3.969593    0.         13.59080056  1.85729332  6.9387189 ]]
